const express = require("express");
const router = express.Router();
const authMiddleware = require("../authMiddleware");
const db = require("../db");
const PDFDocument = require("pdfkit");

router.get("/download", authMiddleware, async (req, res) => {
  try {
    const user_id = req.user.id;
    
    // Fetch all relevant data with safety checks
    const [users] = await db.promise().query("SELECT * FROM users WHERE id = ?", [user_id]);
    if (users.length === 0) {
       return res.status(404).json({ success: false, message: "User profile not found." });
    }
    const user = users[0];
    
    const [recos] = await db.promise().query(
      "SELECT * FROM user_health_logs WHERE user_id = ? ORDER BY created_at DESC LIMIT 1",
      [user_id]
    );
    const latestReco = recos[0] || {};
    
    const [challenges] = await db.promise().query(
      "SELECT * FROM user_challenges WHERE user_id = ? ORDER BY created_at DESC LIMIT 1",
      [user_id]
    );
    const latestChallenge = challenges[0] || {};

    // Create PDF
    const doc = new PDFDocument({ margin: 50 });
    
    // Set headers for download
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=Vitalis_Report_${user.full_name?.replace(/\s+/g, '_')}.pdf`);
    
    doc.pipe(res);

    // Title
    doc.fillColor("#0ea5e9").fontSize(26).text("Vitalis Health Report", { align: "center" });
    doc.moveDown();
    doc.fontSize(10).fillColor("#64748b").text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, { align: "center" });
    doc.moveDown(2);

    // Section 1: User Profile
    doc.fillColor("#1e293b").fontSize(16).text("1. User Profile", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor("#334155");
    doc.text(`Name: ${user.full_name || "N/A"}`);
    doc.text(`Age: ${user.age || "N/A"}`);
    doc.text(`Gender: ${user.gender || "N/A"}`);
    doc.text(`Email: ${user.email}`);
    doc.moveDown();

    // Section 2: Health Summary
    doc.fillColor("#1e293b").fontSize(16).text("2. Health Summary", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor("#334155");
    doc.text(`Weight: ${latestReco.weight ? latestReco.weight + " kg" : "Not recorded"}`);
    doc.text(`Height: ${latestReco.height ? latestReco.height + " cm" : "Not recorded"}`);
    doc.text(`BMI: ${latestReco.bmi || "Not calculated"}`);
    doc.text(`Activity Level: ${user.activity_level || "Sedentary"}`);
    doc.text(`Blood Pressure: ${user.blood_pressure || "Not recorded"}`);
    doc.moveDown();

    // Section 3: Lifestyle & Environment
    doc.fillColor("#1e293b").fontSize(16).text("3. Lifestyle Insights", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor("#334155");
    doc.text(`Daily Water Intake: ${user.water_intake || "Not set"}`);
    doc.text(`Sleep Quality: ${user.sleep_quality || "Not set"}`);
    doc.text(`Stress Level: ${user.stress_level || "Not set"}`);
    doc.moveDown();

    // Section 4: AI Recommendations
    doc.fillColor("#1e293b").fontSize(16).text("4. AI Recommendations", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor("#475569");
    const recommendations = latestReco.recommendations ? latestReco.recommendations.split("STRUCTURED_INSIGHTS")[0] : "No recent recommendations found. Please update your vitals on the dashboard to generate insights.";
    doc.text(recommendations, { align: "justify", lineGap: 2 });
    doc.moveDown();

    // Section 5: Fitness Plan
    doc.fillColor("#1e293b").fontSize(16).text("5. Fitness & Challenges", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor("#334155");
    doc.text(`Current Challenge: ${latestChallenge.challenge_text || "No active challenge"}`);
    doc.text(`Status: ${latestChallenge.completed ? "Completed ✅" : "In Progress ⏳"}`);
    doc.text(`Current Streak: ${latestChallenge.streak || 0} days 🔥`);
    doc.moveDown();

    // Footer
    doc.moveDown(2);
    doc.fontSize(10).fillColor("#94a3b8").text("Disclaimer: This report is generated by Vitalis AI for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.", { align: "center", italic: true });

    doc.end();

  } catch (error) {
    console.error("PDF generation error:", error);
    if (!res.headersSent) {
      res.status(500).json({ success: false, message: "Vitalis encountered an error generating your report. Please try again." });
    }
  }
});

module.exports = router;
